#title in header
title: "ä¸‡è¶£å²›"

#main info
#owner
owner: "æˆ‘å«å®‰é˜³"
info: "ç†æƒ³æ˜¯åšä¸€åè‡ªç”±çš„ç‹¬ç«‹å¼€å‘è€…ï¼Œåœ¨æ­¤åˆ†äº«è®°å½•æˆ‘çš„æ‰€åšæ‰€æƒ³å’Œè‡ªå·±æˆé•¿çš„ç‚¹æ»´"
#description
desc: ""

#menu
menu:
  è¶£å‘³AI: /tags/è¶£å‘³AI/
  å¥‡è¶£å®‡å®™: /tags/å¥‡è¶£å®‡å®™/
  çµæ„Ÿç ”ç©¶æ‰€: /tags/çµæ„Ÿç ”ç©¶æ‰€/


#index/main page max show posts (in number)
max_post: 9
per_page: 12

# Colors use hex color without #
# Theme color
tcolor: 333

# Define path to user css
#(could be also located outside of theme)
# Relative to source/ directory
# usercss: css/user.css

# social profile at the footer/bottom
footer: true
placename: 2015-2025 ä¸‡è¶£å²› |
placelink: http://w3cay.com

# Misc
nanobar: /js/nanobar.min.js
switch_light: â˜€ï¸
switch_dark: ğŸŒ‘

# Picture enlargement
picjs: /js/pic.min.js
highlight_js: /js/highlight.min.js
highlight_css: /css/github.min.css
# favicon
favicon: /images/favicon.ico

article:
  thumbnail: true
thumbnail: /images/android-chrome-192x192.png
twitter: https://twitter.com/AnyangChen
rss: https://w3cay.com/atom.xml

hash:
  enable: true 

tag_cloud:
  path: tags/index.html
  limit: 0  # è®¾ç½®æ˜¾ç¤ºæ ‡ç­¾çš„æ•°é‡ï¼Œ0è¡¨ç¤ºä¸é™åˆ¶
  order: desc  # æ’åºæ–¹å¼ï¼Œdescè¡¨ç¤ºæŒ‰æ ‡ç­¾ä½¿ç”¨æ¬¡æ•°é™åº
  color: false  # æ˜¯å¦å¯ç”¨æ ‡ç­¾é¢œè‰²
  size: 1.2  # æ ‡ç­¾å¤§å°
  font_size: 16  # å­—ä½“å¤§å°